
on:
  issues:
      types: [opened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "step 1"
      - name : step 2
        run: echo "step 2"
  job2:
    name: Job2
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship!'
          color: 'red'